#!/bin/bash

### Stack eer files based on the mdoc file generated by Tomography,EF-facon4.
### Use the relion change eer files to MRC format
### Need to put the mdoc file and the driftcorr mrc files in the different folders
### The extended header just contains the tilt angle information, no intensity and stage positions.
### will read the record binning first, if the original record binning is not 1, this script will change it to 1 automatically. No need to input any varaible.
### Original code by Yunjie Chang 2018-12-20. Changed by You Fu 2023-8-20


for f in ./*.mdoc; do
  prfx=`basename ${f} .mdoc`
  echo; echo ${prfx}

  #get record binning
  RecBin=$(grep "Binning" ${f}| awk 'NR==1 {printf"%d",$8}')
  

  ## get file list
  grep -r "SubFramePath" ${f} | awk -F'\' '{print $NF }' > ${prfx}.st.filelist1 
  sed -i "s/\./\_/g" ${prfx}.st.filelist1
  sed -i "s/_eer/.mrc/g" ${prfx}.st.filelist1
  echo $(cat ${prfx}.st.filelist1|wc -l) > ${prfx}.st.filelist
  awk '{print $0 "\n" 0}' ${prfx}.st.filelist1 >> ${prfx}.st.filelist

  

  ## get title
  if [ ${RecBin} != 1 ]; then
    grep "T =" ${f} | sed -e "s/\[//g" -e "s/\]//g" -e 's,T =,,g' -e 's/ *$//g' -e "s/binning = ${RecBin} /binning = 1 /g" > ${prfx}.st.title
  else
    grep "T =" ${f} | sed -e "s/\[//g" -e "s/\]//g" -e 's,T =,,g' -e 's/ *$//g' > ${prfx}.st.title
  fi

  ## get tilt angles
  extracttilts -tilts -ot ${f} > ${prfx}.st.tilt1
  newstack -q -ti ${prfx}.st.tilt1 -filei ${prfx}.st.filelist ${prfx}.mrc
  alterheader -ti "$(awk '{print $0}' ${prfx}.st.title)" ${prfx}.mrc
  
  ##add header
  rotation=$(grep "RotationAngle" ${f}| awk 'NR==1 {printf"%d",$3}')
  alterheader -ti "Tilt axis rotation angle = ${rotation} " ${prfx}.mrc
  alterheader -ti "By Ava -Zhijie Liu Lab, shanghaitech University" ${prfx}.mrc
  
  alterheader -ti "Original Record Binning = ${RecBin} " ${prfx}.mrc
 
  alterheader -ti "Extended header from Tomography contains:" ${prfx}.mrc
  alterheader -ti "Tilt angles - Extract with extracttilts" ${prfx}.mrc
  #newstack -reorder -1  ${prfx}.mrc  ${prfx}_1.mrc
  newstack -reorder -1  ${prfx}.mrc  ../mrc/${prfx}.mrc
  rm ${prfx}.mrc 
  rm ${prfx}.st.filelist1 ${prfx}.st.filelist   ${prfx}.st.tilt1 ${prfx}.st.title 
done
